### ISSUE TITLE
Codewind view not visible

### ISSUE THREAD

**Issue by slecholineas** [eclipse/codewind-openapi-vscode#17]
Hello, I've installed Codewind on Visual Code 1.36.0, but I'm having the following issues: 

- I can not find a way to get the Codewind View from the Explorer View. How can I enable this view ?
- when using "_OpenAPI: Generate Client from OpenAPI Specification_" I'm not getting any result but unable to get any error log. Same issue with _Generate Server_. How can I check the errors ?

**Codewind in VSCode**
![image](https://user-images.githubusercontent.com/42738911/60721949-bfb37800-9f2f-11e9-83bd-e182b16cce2c.png)

**Content of the Swagger spec**
![image](https://user-images.githubusercontent.com/42738911/60722210-7ca5d480-9f30-11e9-8354-c0d373e517f3.png)

**Comment by keithchong** [comment]
Hi, did you install Codewind for Eclipse as well? 

BTW, step 2 in the instructions is optional (installing Codewind is optional).   In this case, the commands should be available via the palette.   If you had Codewind installed and you had Codewind projects created, then you could access the commands via the context menu of the project.

I suggest to try this without Codewind installed first.

**Comment by keithchong** [comment]
Try renaming your spec file to openapi.yaml and/or try a 3.0 spec?

**Comment by keithchong** [comment]
Check the log file, (on Mac), from you home folder,  Library/Application Support/Code/logs/20190704T235423/exthost4/IBM.codewind-openapi-tools/codewind-openapi-tools.log

**Comment by slecholineas** [comment]
I've found the log file in HOME_FOLDER\AppData\Roaming\Code\logs\20190705T141317\exthost1\IBM.codewind-openapi-tools\ and it contains `[INFO: 14:14:55.089 Logger.js.setLogFilePath():56]: Codewind OpenAPI Tools Logger initialized at c:\Users\lechostn\AppData\Roaming\Code\logs\20190705T141317\exthost1\IBM.codewind-openapi-tools\codewind-openapi-tools.log
`
Do you have an example YAML which works on your side which I could use to check on my side ?

**Comment by slecholineas** [comment]
I've tried with the v3 petstore.yaml from https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0 but without success. Even when I rename it to openapi.yaml it doesn't work.

FYI: I'm simply opening the file in VSCode without adding it to a "project".

**Comment by keithchong** [comment]
Hi @slecholineas , no, the Codewind extension is optional.  I'm using the same VS Code version too.

**Comment by keithchong** [comment]
Hi @slecholineas , try this build.

https://download.eclipse.org/codewind/codewind-openapi-vscode/pr/21/2/?d

**Comment by sghung** [comment]
Closing since there is no further activity in this issue. Please re-open in https://github.com/eclipse/codewind if needed.
